http:
  port: 8080
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  users:
    host: localhost
    path: '/users*'
    methods: 'GET,POST,PUT'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  users:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: getting-started
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  - name: users
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: users
              changeOrigin: true